INSERT INTO "company"."dbo"."ADDRESS" (STREET_1,STREET_2,CITY,PROVINCE,COUNTRY,POSTAL_CODE) VALUES ('181 ANTHONY AVE','TEST SUITE','MISSISSAUGA                       ','ON                  ','CA','L4Z 3V3   ');
INSERT INTO "company"."dbo"."ADDRESS" (STREET_1,STREET_2,CITY,PROVINCE,COUNTRY,POSTAL_CODE) VALUES ('181 YOUNGE AVE','TEST SUITE','TORONTO                       ','ON                  ','CA','M4Z 3V3   ');
INSERT INTO "company"."dbo"."ADDRESS" (STREET_1,STREET_2,CITY,PROVINCE,COUNTRY,POSTAL_CODE) VALUES ('200 ROLLING ST','TEST SUITE','RICHMOND HILL','ON                  ','CA','U4Z 3V3   ');

INSERT INTO "company"."dbo"."CLIENT" (FIRST_NAME,LAST_NAME,EMAIL,PHONE,ADDRESS_ID) VALUES ('JAMES','DEAN','JAMES.DEAN@GMAIL.COM','1-419-333-0000',1);
INSERT INTO "company"."dbo"."CLIENT" (FIRST_NAME,LAST_NAME,EMAIL,PHONE,ADDRESS_ID) VALUES ('MARIA','DELLA','MARIA.DELLA@GMAIL.COM','1-419-444-0000',2);
INSERT INTO "company"."dbo"."CLIENT" (FIRST_NAME,LAST_NAME,EMAIL,PHONE,ADDRESS_ID) VALUES ('UPAL','SAMBARE','UTPAL.SAM@HOT.COM','1-419-555-0000',3);

INSERT INTO "company"."dbo"."ACCOUNT" (PRODUCT_NAME,CLIENT_ID,BALANCE) VALUES ('CHECK     ',1,100.0000);
INSERT INTO "company"."dbo"."ACCOUNT" (PRODUCT_NAME,CLIENT_ID,BALANCE) VALUES ('SAVING    ',2,1030.0000);
INSERT INTO "company"."dbo"."ACCOUNT" (PRODUCT_NAME,CLIENT_ID,BALANCE) VALUES ('RRSP      ',3,10030.0000);

-- RESET QUERY TABLE WITH PRIMARY KEY

DELETE FROM QUERY;
DBCC CHECKIDENT ('QUERY', RESEED, 0);
INSERT INTO QUERY (name,sql,map) VALUES ('SELECT DB_NAME()','SELECT * FROM ACCOUNT WHERE BALANCE < 1000',null);
INSERT INTO QUERY (name,sql,map) VALUES ('rufina test','select * from address where city = ''toronto''',null);
INSERT INTO QUERY (name,sql,map) VALUES ('area check',' select * from client c inner join account a on c.client_id = a.client_id where a.PRODUCT_NAME = ''check''',null);
INSERT INTO QUERY (name,sql,map) VALUES ('bounce test','SELECT * FROM ACCOUNT WHERE BALANCE > {BALANCE} AND PRODUCT_NAME LIKE ''%{PRODUCT}%''','{"BALANCE":"","PRODUCT":""}');

select * from query